/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { forwardRef, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

const Model = (props, ref) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("./models/scene.gltf");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="roomgltf">
          <group
            name="Sketchfab_model"
            position={[-129.25, 0, -35.76]}
            rotation={[-Math.PI / 2, 0, -0.84]}
          >
            <group
              name="50a2fa0af02547dfbe87cc1b2d43bcf1fbx"
              rotation={[Math.PI / 2, 0, 0]}
            >
              <group name="RootNode">
                <group
                  name="Area"
                  position={[-23.36, 604.19, -463.55]}
                  rotation={[-0.86, -0.72, 0.01]}
                  scale={100}
                >
                  <group name="Object_6" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_7" />
                  </group>
                </group>
                <group
                  name="Area001"
                  position={[-62.6, 604.19, 467.87]}
                  rotation={[-2.1, 0.85, 2.9]}
                  scale={100}
                >
                  <group name="Object_9" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_10" />
                  </group>
                </group>
                <group
                  name="Area003"
                  position={[-561.74, 604.19, 35.5]}
                  rotation={[-0.72, 0.53, 1.08]}
                  scale={100}
                >
                  <group name="Object_15" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_16" />
                  </group>
                </group>
                <group
                  name="Area004"
                  position={[1.88, 513.73, 28.93]}
                  rotation={[-0.93, -1.56, -0.96]}
                  scale={100}
                >
                  <group name="Object_18" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_19" />
                  </group>
                </group>
                <group
                  name="Books"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group name="Boxes" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh
                    name="Boxes_B_Tranaparency_0"
                    geometry={nodes.Boxes_B_Tranaparency_0.geometry}
                    material={materials.B_Tranaparency}
                    position={[1.02, 1.61, 3.19]}
                    rotation={[-0.01, -0.07, -0.42]}
                    scale={0.37}
                  />
                </group>
                <group
                  name="Camera001"
                  position={[809.34, 872.25, 578.73]}
                  rotation={[Math.PI, 0.6, 2.48]}
                  scale={100}
                >
                  <group name="Object_4" />
                </group>
                <group
                  name="Cell_phone"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="Desk"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="Dish"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="Eraser"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="Keyboard_wire"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="Mouse_wire"
                  position={[0, 0, -47.15]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="Mousepad"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="Notebook"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="Notebook_wire"
                  position={[0, 0, 290.97]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="Paper"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="PC_Keyboard"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="PC_Monitor"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group name="PC_Mouse" scale={100} />
                <group
                  name="PC_Speaker"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group name="Pen" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              </group>
            </group>
          </group>
          <group
            name="Sketchfab_model001"
            position={[-129.25, 0, -35.76]}
            rotation={[-Math.PI / 2, 0, -0.84]}
          >
            <group name="LowPolyComputerDeskfbx" rotation={[Math.PI / 2, 0, 0]}>
              <group name="RootNode001">
                <group
                  name="CD"
                  position={[-77, 75.08, 57.33]}
                  rotation={[-Math.PI, 1.26, -Math.PI]}
                  scale={0.1}
                />
                <group
                  name="CD_case"
                  position={[-77, 75.36, 57.33]}
                  rotation={[-Math.PI, 1.26, -Math.PI]}
                  scale={0.06}
                />
                <group
                  name="Computer_case"
                  position={[-55.08, 74.82, 31.19]}
                  rotation={[0, 0.04, 0]}
                  scale={0.23}
                />
                <group
                  name="Computer_monitor001"
                  position={[-3.9, 74.82, 28.04]}
                  scale={[0.19, 0.14, 0.1]}
                />
                <group
                  name="Cube000"
                  position={[10.87, 0, 115.73]}
                  rotation={[0, 0.58, 0]}
                  scale={0.39}
                />
                <group name="Drawers" position={[65.1, 0, 55.31]} />
                <group
                  name="Floppy_disk"
                  position={[-41.91, 74.82, 65.87]}
                  rotation={[Math.PI / 2, 0, 0.25]}
                />
                <group
                  name="Keyboard"
                  position={[-3.76, 74.82, 55.9]}
                  scale={0.31}
                />
                <group name="KeyboardCable" position={[34.33, 76.16, 56.06]} />
                <group name="Monitor_cable" position={[-3.9, 74.82, 28.04]} />
                <group
                  name="Mouse"
                  position={[34.33, 76.16, 56.06]}
                  scale={0.27}
                />
                <group name="Mouse_cord" position={[34.33, 76.16, 56.06]} />
                <group
                  name="Mousepad001"
                  position={[42.96, 74.82, 54.26]}
                  rotation={[0, -0.12, 0]}
                  scale={0.15}
                />
                <group name="Office_desk" scale={0.27} />
                <group
                  name="Paper001"
                  position={[74.85, 74.63, 39.72]}
                  rotation={[0, 0.12, 0]}
                  scale={0.1}
                />
                <group
                  name="Paper2"
                  position={[76.15, 75, 39.72]}
                  rotation={[0, 0.03, 0]}
                  scale={0.1}
                />
                <group
                  name="Pen001"
                  position={[76.51, 76.01, 45.56]}
                  rotation={[0, 0.24, 0]}
                  scale={0.01}
                />
                <group
                  name="Phone_stand"
                  position={[50.7, 74.82, 18.87]}
                  rotation={[0, -0.19, 0]}
                />
                <group
                  name="Phonehandle"
                  position={[46.95, 79.24, 18.51]}
                  rotation={[0.17, -0.19, 0.03]}
                  scale={0.26}
                />
                <group
                  name="SpeakerL"
                  position={[27.42, 74.82, 27.43]}
                  rotation={[0, -0.1, 0]}
                  scale={0.18}
                />
                <group
                  name="SpeakerR"
                  position={[-33.15, 74.82, 31.87]}
                  rotation={[0, 0.45, 0]}
                  scale={0.18}
                />
                <group name="Speakers_cable" position={[27.42, 74.82, 27.43]} />
              </group>
            </group>
          </group>
          <group
            name="Sketchfab_model002"
            position={[0, 20, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group
              name="8e4fdc9bc0e74a2393198690eb38483dfbx"
              position={[-13232.61, 3661.06, 0]}
              rotation={[Math.PI / 2, -0.84, 0]}
            >
              <group name="RootNode002">
                <group
                  name="Curve"
                  position={[-0.11, 0.14, 0]}
                  rotation={[-1.55, 0, -Math.PI]}
                  scale={100}
                />
                <group
                  name="Macbook"
                  position={[0, 5, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={50000}
                />
              </group>
            </group>
          </group>
          <group
            name="Sketchfab_model003"
            position={[-184.69, 0, -191.99]}
            rotation={[-Math.PI / 2, 0, -2.36]}
          >
            <group name="root" scale={250}>
              <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
                <group name="Chair003_0" />
              </group>
            </group>
          </group>
          <group
            name="Sketchfab_model004"
            position={[-344.06, 162.06, -378.98]}
            rotation={[-Math.PI / 2, 0, 1.03]}
          >
            <group name="85334b9f59734402a7165e02a2ee8479objcleaner" />
          </group>
          <group
            name="Sketchfab_model005"
            position={[-108.62, 161.32, -450.78]}
            rotation={[-Math.PI / 2, 0, -1.55]}
            scale={[2000, 2000, 1250]}
          >
            <group
              name="356e21ee1f1e40c6828fcd2e1a3a355bfbx"
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}
            >
              <group name="RootNode003">
                <group name="Curved_Monitor">
                  <group
                    name="Curved_Monitor001"
                    position={[2.05, 4.94, 0]}
                    rotation={[0, 0, 0.12]}
                    scale={[0.26, 7.46, 15.13]}
                  />
                  <group name="Peana" position={[0.08, 0, 0]} />
                </group>
              </group>
            </group>
          </group>
          <group
            name="Sketchfab_model006"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={150}
          >
            <group
              name="2fa215a9881f48e6825a4215b35a139bfbx"
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}
            >
              <group name="RootNode004">
                <group
                  name="Cube002"
                  position={[0, 35.25, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
              </group>
            </group>
          </group>
          <group name="Sketchfab_model007" rotation={[-Math.PI / 2, 0, 0]}>
            <group
              name="78668c07495a4300b30052cef89ff599fbx"
              rotation={[Math.PI / 2, 0, 0]}
            >
              <group name="RootNode005">
                <group name="StickyNotes">
                  <group
                    name="pPlane3"
                    position={[373.58, 207.95, -467.77]}
                    rotation={[1.38, -0.18, 0.77]}
                    scale={19.67}
                  />
                  <group
                    name="pPlane4"
                    position={[394.61, 219.52, -447.74]}
                    rotation={[1.38, -0.18, 0.77]}
                    scale={19.67}
                  />
                  <group
                    name="pPlane5"
                    position={[391.39, 187.03, -450.13]}
                    rotation={[1.38, -0.18, 0.77]}
                    scale={19.67}
                  />
                </group>
              </group>
            </group>
          </group>
          <group
            name="Sketchfab_model008"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={10}
          >
            <group
              name="8fa177081e164aec8035a942210e3bddfbx"
              rotation={[Math.PI / 2, 0, 0]}
            >
              <group name="RootNode006">
                <group
                  name="books"
                  position={[-3.08, 4.64, -1.4]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <group
                    name="book"
                    position={[3.08, 0.15, 0.05]}
                    rotation={[Math.PI / 2, Math.PI / 2, 0]}
                  />
                  <group
                    name="book001"
                    position={[4.96, 0.15, 0.05]}
                    rotation={[Math.PI / 2, Math.PI / 2, 0]}
                  />
                  <group
                    name="book002"
                    position={[6.85, 0.15, 0.05]}
                    rotation={[Math.PI / 2, Math.PI / 2, 0]}
                  />
                  <group
                    name="book003"
                    position={[10.25, 0.15, -0.34]}
                    rotation={[0, 1.13, Math.PI / 2]}
                  />
                  <group
                    name="book004"
                    position={[14.32, 0.15, -1.46]}
                    rotation={[0, 0.7, Math.PI / 2]}
                  />
                  <group
                    name="book006"
                    position={[-24.7, 0.15, 0.05]}
                    rotation={[Math.PI / 2, Math.PI / 2, 0]}
                  />
                  <group
                    name="book007"
                    position={[-22.64, 0.15, 0.05]}
                    rotation={[Math.PI / 2, Math.PI / 2, 0]}
                  />
                  <group
                    name="book008"
                    position={[-1.05, 0.15, -2.11]}
                    rotation={[-Math.PI, 0, -Math.PI / 2]}
                  />
                  <group
                    name="book009"
                    position={[-1.05, 0.15, -0.34]}
                    rotation={[-Math.PI, 0, -Math.PI / 2]}
                  />
                </group>
                <group
                  name="mug"
                  position={[0, 0, -0.54]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <group
                  name="shelf"
                  position={[0, 0, -0.54]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
              </group>
            </group>
          </group>
          <group
            name="Sketchfab_model009"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={300}
          >
            <group
              name="Collada_visual_scene_group"
              rotation={[Math.PI / 2, 0, 0]}
            >
              <group name="pCube8" />
              <group name="pCube9" />
              <group name="pCylinder14" />
              <group name="pCylinder5" />
              <group name="polySurface11" />
              <group name="polySurface14" />
              <group name="polySurface15" />
              <group name="polySurface16" />
              <group name="polySurface17" />
              <group name="polySurface18" />
              <group name="polySurface19" />
              <group name="polySurface20" />
              <group name="polySurface21" />
              <group name="polySurface22" />
              <group name="polySurface23" />
              <group name="polySurface24" />
              <group name="polySurface25" />
              <group name="polySurface26" />
              <group name="polySurface27" />
              <group name="polySurface28" />
              <group name="polySurface29" />
              <group name="polySurface30" />
              <group name="polySurface31" />
              <group name="polySurface7" />
              <group name="polySurface8" />
            </group>
          </group>
          <group
            name="Sketchfab_model010"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={35}
          >
            <group name="Root">
              <group
                name="Cylinder"
                position={[-2.88, 9.61, 4.7]}
                rotation={[1.57, 1.32, -1.6]}
                scale={[0.06, 0.06, 1.52]}
              />
              <group
                name="Plane"
                position={[0.08, 9.51, 4.62]}
                rotation={[0, 0, 0.83]}
                scale={[0.19, 0.37, 0.53]}
              />
            </group>
          </group>
          <group
            name="Sketchfab_model011"
            position={[-409.85, 272.56, -262.63]}
            rotation={[-2.14, 1.24, 0.55]}
            scale={0.25}
          >
            <group
              name="Apple_Watch_S4_Sport_44mm_SpaceGrey_AlFBX"
              rotation={[Math.PI / 2, 0, 0]}
            >
              <group name="RootNode007">
                <group
                  name="Back_cover"
                  position={[-1.71, -0.74, 4.58]}
                  rotation={[0, 0, 0.06]}
                  scale={0.91}
                />
                <group
                  name="Button"
                  position={[16.25, 8.34, 10.53]}
                  rotation={[Math.PI / 2, Math.PI / 2, 0]}
                  scale={[0.99, 0.99, 0.89]}
                />
                <group name="Cap" position={[-1.71, 1.56, 10.09]}>
                  <group name="Object_28" position={[0, 0, -5.35]} />
                </group>
                <group name="Case" position={[-1.71, -0.15, 10.09]}>
                  <group name="Object_8" position={[0, 0, -5.35]} />
                </group>
                <group name="Case_2" position={[-1.71, -0.15, 14.31]}>
                  <group name="Object_22" position={[0, 0, -9.57]} />
                </group>
                <group name="Glass" position={[-1.71, -0.15, 4.74]} />
                <group
                  name="Rivet"
                  position={[-1.96, -6.06, -44.51]}
                  scale={0.99}
                >
                  <group name="Object_18001" position={[0, 5.98, 49.03]} />
                </group>
                <group name="Screen" position={[-1.71, -0.15, 14.24]}>
                  <group name="Object_33" position={[0, 0, -9.57]} />
                </group>
                <group
                  name="Sensor"
                  position={[-1.71, -0.74, 3.93]}
                  rotation={[0, 0, 0.06]}
                  scale={0.91}
                />
                <group
                  name="Strap"
                  position={[-1.81, -0.12, 4.6]}
                  scale={0.99}
                />
              </group>
            </group>
          </group>
          <group
            name="Sketchfab_model012"
            position={[-443.32, 273.63, 166.31]}
            rotation={[-Math.PI / 2, 0, 1.56]}
            scale={2.5}
          >
            <group name="window433DS">
              <group name="frame43" position={[33.86, 0.91, 40.49]}>
                <group
                  name="3DSMeshMatrix003"
                  position={[-33.86, -0.91, -40.49]}
                />
              </group>
              <group name="frame4w" position={[-21.04, 0.02, 38.46]}>
                <group
                  name="3DSMeshMatrix002"
                  position={[21.04, -0.02, -38.46]}
                />
                <group name="frame430" position={[21.04, 0.8, -0.31]}>
                  <group
                    name="3DSMeshMatrix001"
                    position={[0, -0.83, -38.16]}
                  />
                </group>
              </group>
              <group name="Plane01" position={[-13.94, 292.43, -3.87]}>
                <group
                  name="3DSMeshMatrix"
                  position={[-100.52, -292.34, 3.87]}
                />
              </group>
            </group>
          </group>
          <group
            name="Sketchfab_model013"
            position={[-299.12, 407.5, -469.41]}
            rotation={[-1.59, 0, 0]}
            scale={250}
          >
            <group
              name="b4e35eeb695e4e679f18cc2ed1ed884dfbx"
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}
            >
              <group name="RootNode008">
                <group
                  name="Cube003"
                  position={[0, 44.23, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={[20, 0.5, 40]}
                />
              </group>
            </group>
          </group>
          <group
            name="Sketchfab_model014"
            position={[5.82, 501.08, -461.81]}
            rotation={[-0.34, 0.01, -0.4]}
            scale={400}
          >
            <group name="root001">
              <group
                name="GLTF_SceneRootNode001"
                rotation={[Math.PI / 2, 0, 0]}
              >
                <group
                  name="VINYL051_50"
                  position={[0, 0, 0.1]}
                  rotation={[0, 0.44, 0]}
                />
                <group
                  name="vinyl_52"
                  position={[0.19, 0, 0]}
                  rotation={[0, -1.47, 0]}
                >
                  <group name="label_51" />
                </group>
              </group>
            </group>
          </group>
          <group
            name="Sketchfab_model015"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={50}
          >
            <group name="root002">
              <group
                name="GLTF_SceneRootNode002"
                rotation={[Math.PI / 2, 0, 0]}
              >
                <group
                  name="Big_left_2"
                  position={[-1.01, 0, 0]}
                  rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                  scale={1.26}
                />
                <group
                  name="Big_Right_1"
                  position={[1.01, 0, 0]}
                  rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                  scale={1.26}
                />
                <group name="Handle_0" rotation={[0, 1.57, 0]}>
                  <group
                    name="Object_4001"
                    position={[-3.45, 10.87, 10.43]}
                    rotation={[1.07, -0.21, 0.37]}
                    scale={0}
                  >
                    <mesh
                      name="Object_0004"
                      geometry={nodes.Object_0004.geometry}
                      material={materials.Metal_Shiny}
                    />
                    <mesh
                      name="Object_0004_1"
                      geometry={nodes.Object_0004_1.geometry}
                      material={materials["Material.047"]}
                    />
                    <mesh
                      name="Object_0004_2"
                      geometry={nodes.Object_0004_2.geometry}
                      material={materials["Material.048"]}
                    />
                    <mesh
                      name="Object_0004_3"
                      geometry={nodes.Object_0004_3.geometry}
                      material={materials.hidden_material}
                    />
                    <mesh
                      name="Object_0004_4"
                      geometry={nodes.Object_0004_4.geometry}
                      material={materials["Material.029"]}
                    />
                    <mesh
                      name="Object_0004_5"
                      geometry={nodes.Object_0004_5.geometry}
                      material={materials["Material.001"]}
                    />
                    <mesh
                      name="Object_0004_6"
                      geometry={nodes.Object_0004_6.geometry}
                      material={materials["Material.003"]}
                    />
                    <mesh
                      name="Object_0004_7"
                      geometry={nodes.Object_0004_7.geometry}
                      material={materials["Material.015"]}
                    />
                    <mesh
                      name="Object_0004_8"
                      geometry={nodes.Object_0004_8.geometry}
                      material={materials["Material.043"]}
                    />
                    <mesh
                      name="Object_0004_9"
                      geometry={nodes.Object_0004_9.geometry}
                      material={materials["Material.014"]}
                    />
                    <mesh
                      name="Object_0004_10"
                      geometry={nodes.Object_0004_10.geometry}
                      material={materials["Material.021"]}
                    />
                    <mesh
                      name="Object_0004_11"
                      geometry={nodes.Object_0004_11.geometry}
                      material={materials["Material.025"]}
                    />
                    <mesh
                      name="Object_0004_12"
                      geometry={nodes.Object_0004_12.geometry}
                      material={materials["Material.023"]}
                    />
                    <mesh
                      name="Object_0004_13"
                      geometry={nodes.Object_0004_13.geometry}
                      material={materials["Material.024"]}
                    />
                    <mesh
                      name="Object_0004_14"
                      geometry={nodes.Object_0004_14.geometry}
                      material={materials["Material.027"]}
                    />
                    <mesh
                      name="Object_0004_15"
                      geometry={nodes.Object_0004_15.geometry}
                      material={materials["Material.028"]}
                    />
                    <mesh
                      name="Object_0004_16"
                      geometry={nodes.Object_0004_16.geometry}
                      material={materials["Material.030"]}
                    />
                    <mesh
                      name="Object_0004_17"
                      geometry={nodes.Object_0004_17.geometry}
                      material={materials["Material.031"]}
                    />
                    <mesh
                      name="Object_0004_18"
                      geometry={nodes.Object_0004_18.geometry}
                      material={materials["Material.049"]}
                    />
                    <mesh
                      name="Object_0004_19"
                      geometry={nodes.Object_0004_19.geometry}
                      material={materials["Material.050"]}
                    />
                    <mesh
                      name="Object_0004_20"
                      geometry={nodes.Object_0004_20.geometry}
                      material={materials["Material.051"]}
                    />
                    <mesh
                      name="Object_0004_21"
                      geometry={nodes.Object_0004_21.geometry}
                      material={materials["Material.052"]}
                    />
                    <mesh
                      name="Object_0004_22"
                      geometry={nodes.Object_0004_22.geometry}
                      material={materials["Material.032"]}
                    />
                    <mesh
                      name="Object_0004_23"
                      geometry={nodes.Object_0004_23.geometry}
                      material={materials["Material.026"]}
                    />
                    <mesh
                      name="Object_0004_24"
                      geometry={nodes.Object_0004_24.geometry}
                      material={materials["Material.017"]}
                    />
                    <mesh
                      name="Object_0004_25"
                      geometry={nodes.Object_0004_25.geometry}
                      material={materials["Material.037"]}
                    />
                    <mesh
                      name="Object_0004_26"
                      geometry={nodes.Object_0004_26.geometry}
                      material={materials["Material.038"]}
                    />
                    <mesh
                      name="Object_0004_27"
                      geometry={nodes.Object_0004_27.geometry}
                      material={materials["Material.044"]}
                    />
                    <mesh
                      name="Object_0004_28"
                      geometry={nodes.Object_0004_28.geometry}
                      material={materials["Material.046"]}
                    />
                    <mesh
                      name="Object_0004_29"
                      geometry={nodes.Object_0004_29.geometry}
                      material={materials["Material.045"]}
                    />
                    <mesh
                      name="Object_0004_30"
                      geometry={nodes.Object_0004_30.geometry}
                      material={nodes.Object_0004_30.material}
                    />
                    <mesh
                      name="Object_0004_31"
                      geometry={nodes.Object_0004_31.geometry}
                      material={materials["Material.053"]}
                    />
                    <mesh
                      name="Object_0004_32"
                      geometry={nodes.Object_0004_32.geometry}
                      material={materials.PC_Speakers}
                    />
                    <mesh
                      name="Object_0004_33"
                      geometry={nodes.Object_0004_33.geometry}
                      material={materials.Books}
                    />
                    <mesh
                      name="Object_0004_34"
                      geometry={nodes.Object_0004_34.geometry}
                      material={materials.ComputerDesk}
                    />
                    <mesh
                      name="Object_0004_35"
                      geometry={nodes.Object_0004_35.geometry}
                      material={materials["Material.008"]}
                    />
                    <mesh
                      name="Object_0004_36"
                      geometry={nodes.Object_0004_36.geometry}
                      material={materials.wire_224198087}
                    />
                    <mesh
                      name="Object_0004_37"
                      geometry={nodes.Object_0004_37.geometry}
                      material={materials["Material.016"]}
                    />
                    <mesh
                      name="Object_0004_38"
                      geometry={nodes.Object_0004_38.geometry}
                      material={materials.lambert28}
                    />
                    <mesh
                      name="Object_0004_39"
                      geometry={nodes.Object_0004_39.geometry}
                      material={materials.lambert29}
                    />
                    <mesh
                      name="Object_0004_40"
                      geometry={nodes.Object_0004_40.geometry}
                      material={materials.lambert30}
                    />
                    <mesh
                      name="Object_0004_41"
                      geometry={nodes.Object_0004_41.geometry}
                      material={materials["Material.007"]}
                    />
                    <mesh
                      name="Object_0004_42"
                      geometry={nodes.Object_0004_42.geometry}
                      material={materials["Material.002"]}
                    />
                    <mesh
                      name="Object_0004_43"
                      geometry={nodes.Object_0004_43.geometry}
                      material={materials["Material.009"]}
                    />
                    <mesh
                      name="Object_0004_44"
                      geometry={nodes.Object_0004_44.geometry}
                      material={materials["Material.010"]}
                    />
                    <mesh
                      name="Object_0004_45"
                      geometry={nodes.Object_0004_45.geometry}
                      material={materials["Material.011"]}
                    />
                    <mesh
                      name="Object_0004_46"
                      geometry={nodes.Object_0004_46.geometry}
                      material={materials["Material.006"]}
                    />
                    <mesh
                      name="Object_0004_47"
                      geometry={nodes.Object_0004_47.geometry}
                      material={materials.Iron_Clean}
                    />
                    <mesh
                      name="Object_0004_48"
                      geometry={nodes.Object_0004_48.geometry}
                      material={materials.Iron_Clean2}
                    />
                    <mesh
                      name="Object_0004_49"
                      geometry={nodes.Object_0004_49.geometry}
                      material={materials.Black2}
                    />
                    <mesh
                      name="Object_0004_50"
                      geometry={nodes.Object_0004_50.geometry}
                      material={materials.Rubber}
                    />
                    <mesh
                      name="Object_0004_51"
                      geometry={nodes.Object_0004_51.geometry}
                      material={materials.Black_Glossy2}
                    />
                    <mesh
                      name="Object_0004_52"
                      geometry={nodes.Object_0004_52.geometry}
                      material={materials.Black_Glossy}
                    />
                    <mesh
                      name="Object_0004_53"
                      geometry={nodes.Object_0004_53.geometry}
                      material={materials.Glass_Clear2}
                    />
                    <mesh
                      name="Object_0004_54"
                      geometry={nodes.Object_0004_54.geometry}
                      material={materials.Iron_Clean3}
                    />
                    <mesh
                      name="Object_0004_55"
                      geometry={nodes.Object_0004_55.geometry}
                      material={materials.Black_Glossy_TEXT}
                    />
                    <mesh
                      name="Object_0004_56"
                      geometry={nodes.Object_0004_56.geometry}
                      material={materials.Material_2034}
                    />
                    <mesh
                      name="Object_0004_57"
                      geometry={nodes.Object_0004_57.geometry}
                      material={materials.Material_1898}
                    />
                    <mesh
                      name="Object_0004_58"
                      geometry={nodes.Object_0004_58.geometry}
                      material={materials.Glass_Clear}
                    />
                    <mesh
                      name="Object_0004_59"
                      geometry={nodes.Object_0004_59.geometry}
                      material={materials.Screen_1}
                    />
                    <mesh
                      name="Object_0004_60"
                      geometry={nodes.Object_0004_60.geometry}
                      material={materials["Material.040"]}
                    />
                    <mesh
                      name="Object_0004_61"
                      geometry={nodes.Object_0004_61.geometry}
                      material={materials.vinyl}
                    />
                    <mesh
                      name="Object_0004_62"
                      geometry={nodes.Object_0004_62.geometry}
                      material={materials.label_front}
                    />
                    <mesh
                      name="Object_0004_63"
                      geometry={nodes.Object_0004_63.geometry}
                      material={materials["Material.020"]}
                    />
                    <mesh
                      name="Object_0004_64"
                      geometry={nodes.Object_0004_64.geometry}
                      material={materials["Material.019"]}
                    />
                    <mesh
                      name="Object_0004_65"
                      geometry={nodes.Object_0004_65.geometry}
                      material={materials["Rubber.001"]}
                    />
                    <mesh
                      name="Object_0004_66"
                      geometry={nodes.Object_0004_66.geometry}
                      material={materials.lambert2}
                    />
                    <mesh
                      name="Object_0004_67"
                      geometry={nodes.Object_0004_67.geometry}
                      material={materials["SVGMat.003"]}
                    />
                    <mesh
                      name="Object_0004_68"
                      geometry={nodes.Object_0004_68.geometry}
                      material={materials["SVGMat.004"]}
                    />
                    <mesh
                      name="Object_0004_69"
                      geometry={nodes.Object_0004_69.geometry}
                      material={materials["SVGMat.005"]}
                    />
                    <mesh
                      name="Object_0004_70"
                      geometry={nodes.Object_0004_70.geometry}
                      material={materials["Monitor.003"]}
                    />
                    <mesh
                      name="Object_0004_71"
                      geometry={nodes.Object_0004_71.geometry}
                      material={materials["Material.035"]}
                    />
                    <mesh
                      name="Object_0004_72"
                      geometry={nodes.Object_0004_72.geometry}
                      material={materials["Apple_Logo.001"]}
                    />
                    <mesh
                      name="Object_0004_73"
                      geometry={nodes.Object_0004_73.geometry}
                      material={materials["Body_Bottom.001"]}
                    />
                    <mesh
                      name="Object_0004_74"
                      geometry={nodes.Object_0004_74.geometry}
                      material={materials["Body_Top.001"]}
                    />
                    <mesh
                      name="Object_0004_75"
                      geometry={nodes.Object_0004_75.geometry}
                      material={materials["Body_Side.001"]}
                    />
                  </group>
                </group>
                <group
                  name="Small_Left_4"
                  position={[-1.18, 0, 0]}
                  rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                  scale={1.26}
                />
                <group
                  name="Small_Right_3"
                  position={[1.18, 0, 0]}
                  rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                  scale={1.26}
                />
                <group
                  name="Top_Left_6"
                  position={[-2.69, 0, 0]}
                  rotation={[0, 1.57, 0]}
                />
                <group
                  name="Top_Right_5"
                  position={[-0.02, 0, 0]}
                  rotation={[0, 1.57, 0]}
                />
              </group>
            </group>
          </group>
          <group
            name="Sketchfab_model016"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 50, 50]}
          >
            <group name="Bookshelfobjcleanermaterialmergergles" />
          </group>
          <group
            name="Sketchfab_model017"
            position={[0, 500, -10]}
            rotation={[-Math.PI / 2, 0, -3.14]}
            scale={200}
          >
            <group name="fanfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
              <group name="Object_2002">
                <group name="RootNode009">
                  <group
                    name="Base"
                    position={[0, 53.1, 0]}
                    rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                    scale={100}
                  />
                  <group
                    name="BezierCurve001"
                    position={[0, 53.1, -7]}
                    rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                    scale={100}
                  />
                  <group name="Head" position={[0, 53.1, 0]} scale={100}>
                    <group name="Helix" position={[0, 0, -0.07]} />
                    <group
                      name="BezierCurve"
                      position={[0, 0.05, 0.07]}
                      rotation={[-Math.PI / 2, 1.57, 0]}
                    />
                    <group
                      name="Handle"
                      position={[0, 0, 0.01]}
                      rotation={[Math.PI, 0, Math.PI / 2]}
                    />
                    <group
                      name="Switch"
                      position={[0.03, -0.06, -0.05]}
                      rotation={[-Math.PI / 2, 0, 0]}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
          <group
            name="Sketchfab_model018"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[75, 100, 200]}
          >
            <group name="WINDOWS_BLINDSobjcleanermaterialmergergles" />
          </group>
          <group
            name="Sketchfab_model019"
            position={[0, -35.91, -0.02]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={2.25}
          >
            <group
              name="a3c1c2c87fb6437ea9d163918f1fd80afbx"
              rotation={[-Math.PI, 0, 0]}
            >
              <group name="RootNode010">
                <group
                  name="Mesh"
                  position={[-0.26, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.36}
                />
              </group>
            </group>
          </group>
          <group name="Sketchfab_model020" rotation={[-Math.PI / 2, 0, 0]}>
            <group
              name="5a6dbae59ab84adc85502e644c55dc8efbx"
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}
            >
              <group name="RootNode011">
                <group
                  name="Lockers21168"
                  position={[25565.57, 424.52, -257.88]}
                  rotation={[-Math.PI, 0, 0]}
                  scale={-9.46}
                />
              </group>
            </group>
          </group>
          <group
            name="Sketchfab_model021"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group
              name="8e4fdc9bc0e74a2393198690eb38483dfbx001"
              rotation={[Math.PI / 2, 0, 0]}
            >
              <group name="RootNode012">
                <group
                  name="Curve001"
                  position={[-0.11, 0.14, 0]}
                  rotation={[-1.55, 0, -Math.PI]}
                  scale={100}
                />
                <group
                  name="Macbook001"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
              </group>
            </group>
          </group>
          <pointLight
            name="Point"
            intensity={1000000}
            decay={2}
            color="#ff570b"
            position={[-102.89, 377.51, -30.05]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <spotLight
            name="Spot"
            intensity={500000}
            angle={0.58}
            penumbra={0.15}
            decay={2}
            color="#ff7821"
            position={[121.95, 386.11, -138.57]}
            rotation={[-1.23, 0.08, -0.01]}
          >
            <group position={[0, 0, -1]} />
            <group position={[0, 0, -1]} />
          </spotLight>
          <spotLight
            name="Spot001_1"
            intensity={500000}
            angle={0.58}
            penumbra={0.15}
            decay={2}
            color="#ff7821"
            position={[79.28, 386.87, -137.27]}
            rotation={[-1.23, 0.08, -0.01]}
          >
            <group position={[0, 0, -1]} />
            <group position={[0, 0, -1]} />
          </spotLight>
          <mesh
            name="tree001"
            geometry={nodes.tree001.geometry}
            material={materials["Material.012"]}
            position={[137.46, 185.01, -108.47]}
            scale={0.75}
          />
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("./models/scene.gltf");

export default forwardRef(Model);
